services:
  managarr:
    build: .
    container_name: managarr
    restart: unless-stopped
    ports:
      - "3005:3005"
    env_file:
      - /mnt/user/appdata/managarr/.env
    environment:
      NODE_ENV: production
